# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\\
        EShopMicroservices\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\EShopMicroservices\\\
      src\\Services\\Basket\\Basket.API:/app:rw"
    - "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\EShopMicroservices\\\
      src:/src:rw"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\User\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_30_12_42_09:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\\
        EShopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\EShopMicroservices\\\
      src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "D:\\Education\\CSharp\\Microservices\\UdemyProjects\\SuperSmartCourse\\EShopMicroservices\\\
      src:/src:rw"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\User\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_6_30_12_42_09:/var/opt/rider-debugger:rw"
    working_dir: "/app"
